
spring:
  datasource:
    hikari:
      connection-test-query=SELECT 1
    url: jdbc:h2:tcp://localhost/~/phone-book
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace